### PR TITLE
Fix for removed or blocked videos

### PR DESCRIPTION
**Pull request by Kimosabe**
There is no dwonload button if you start from page with removed or blocked video.

URL for example: http://www.youtube.com/watch?v=38peWm76l-U
You'll find error "scriptURL is null" in console and if you'll try to search for another video and open it in current tab, there will be no button.

### CODE REVIEW

**Comment by gantt** [comment]
Thanks for your bug report.

I think the issue is caused by the line 131:

```javascript
     injectScript ('document.getElementById("'+DEBUG_ID+'2").appendChild(document.createTextNode(\'"video_id":"\'+ytplayer.config.args.video_id+\'", "js":"\'+ytplayer.config.assets.js+\'", "dashmpd":"\'+ytplayer.config.args.dashmpd+\'", "url_encoded_fmt_stream_map":"\'+ytplayer.config.args.url_encoded_fmt_stream_map+\'", "adaptive_fmts":"\'+ytplayer.config.args.adaptive_fmts+\'"\'));');
```
I fixed by replacing it with:

```javascript
injectScript('if(ytplayer&&ytplayer.config&&ytplayer.config.args){document.getElementById("' + DEBUG_ID + '2").'+
      'appendChild(document.createTextNode(\'"video_id":"\'+ytplayer.config.args.video_id+\'", "js":"\'+ytplayer.config.assets.js+\'", '+
      '"dashmpd":"\'+ytplayer.config.args.dashmpd+\'", "url_encoded_fmt_stream_map":"\'+ytplayer.config.args.url_encoded_fmt_stream_map+\'", '+
      '"adaptive_fmts":"\'+ytplayer.config.args.adaptive_fmts+\'"\'))};');
```

**Comment by Kimosabe** [comment]
Hmm.. Didn't work for me.

To be clear, here are reproduction steps:
1. Open blocked or removed video by direct link, without that youtube's
ajax (http://www.youtube.com/watch?v=38peWm76l-U)
2. Search something using search field from above, so result will be loaded
via ajax
3. Click any video, which also will be loaded via ajax
4. There is no download button under the player


2015-05-14 20:19 GMT+06:00 gantt <notifications@github.com>:

**Comment by Kimosabe** [comment]
Looks like it works now, thank you!

**Comment by gantt** [comment]
You are right. I included your fix in 1.8.2.

**Pull request closed without merging**
